Repository trailofbits/blight, pull requests merged in 2022-06, with the labels that each got.

#43434 Fixes `FindOutput` and `FindInput` actions in journaling mode
  src/blight/actions/find_inputs.py
  src/blight/actions/find_outputs.py
  src/blight/util.py
  test/actions/test_find_inputs.py
  test/test_util.py
Labels: bug

#43437 workflows/ci: add pip-audit
  .github/workflows/ci.yml
Labels: C:ci/qa

#43438 workflows/ci: bump gh-action-pip-audit
  .github/workflows/ci.yml
Labels: C:ci/qa

#43439 `pip-audit` workflow
  .github/workflows/pip-audit.yml
Labels: C:ci/qa

#43440 Support for fingerprinting the compiler
  src/blight/enums.py
  src/blight/tool.py
  test/test_tool.py
Labels: C:core
